import type { Metadata } from "next";
import "./globals.css";
import { WalletProviders } from "../components/WalletProviders";
import { Navbar } from "../components/Navbar";
import { ThemeProvider } from "../components/ThemeProvider";
import { ToastProvider } from "../components/ToastProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  <body className={`antialiased min-h-screen flex flex-col bg-neutral-950 text-neutral-50`}>        
  <ThemeProvider>
  <WalletProviders>
  <ToastProvider>
          <Navbar />
          <div className="flex-1">
            {children}
          </div>
          <footer className="px-6 py-10 text-center text-[11px] text-neutral-600 border-t border-neutral-900 mt-16">Prototype – Not Production Code</footer>
  </ToastProvider>
  </WalletProviders>
  </ThemeProvider>
      </body>
    </html>
  );
}
